# Generated by Django 3.2.13 on 2022-12-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
