# Generated by Django 3.2.18 on 2023-03-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20230306_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_comments', to='tweets.tweet'),
            preserve_default=False,
        ),
    ]
